
application:
  name: 'faceSwapper'
  url: 'http://locahlost:5000'
  config_file : 'config.yaml'
  
  uploader:
    face_uploader:
      url: "/upload"
    face_uploads:
      url: "/uploads"
    allowed_extensions: ['png', 'jpg', 'jpeg', 'gif',
                         'mp4', 'mov', 'avi', 'mkv']

  swapper:
    face_swap:
      url: '/api/face/swapper/swap'
    model:
      url: 'https://huggingface.co/hacksider/deep-live-cam/blob/main/inswapper_128_fp16.onnx' # URL for inswapper model
      name: 'inswapper_128_fp16.onnx'

  enhancer:
    face_enhance:
      url: '/api/face/enhancer/enhance'
    model:
      url: 'https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth' # URL for inswapper model
      name: 'GFPGANv1.4.pth'
  
  extractor:
    face_extract:
      url: '/api/face/extractor/extract'
      count: 2

  video:
    slices: 10
    skips_in_s: 3
