import os
import subprocess
from textwrap import dedent

import setuptools
from setuptools import find_packages
from setuptools import setup

app = 'faceSwapper'

TOP_DIR = os.path.realpath(os.path.dirname(__file__))
SRC_DIR = os.path.join(TOP_DIR, app)

with open(os.path.join(TOP_DIR, 'VERSION_NUMBER')) as version_file:
    version = version_file.read().strip()

try:
    git_version = (
        subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=TOP_DIR)
        .decode('ascii')
        .strip()
    )
except (OSError, subprocess.CalledProcessError):
    git_version = None

with open(os.path.join(SRC_DIR, 'version.py'), 'w') as f:
    f.write(
        dedent(
            """\
  # This file is generated by setup.py. DO NOT EDIT!
  from __future__ import absolute_import
  from __future__ import division
  from __future__ import print_function
  from __future__ import unicode_literals
  version = '{}'
  git_version = '{}'
  """.format(
                version, git_version
            )
        )
    )

setup(
    name=app,
    version=version,
    description='My Face Swap Implementation',
    # install_requires=[
    #     "PyYAML", "tensorflow_addons", "tensorflow_probability"
    # ],
    # entry_points={
    #     "console_scripts": [
    #         "onnx-tf=onnx_tf.cli:main",
    #     ],
    # },
    # url='https://github.com/onnx/onnx-tensorflow/',
    author='noahximus',
    author_email='noahximus@gmail.com',
    license='Apache License 2.0',
    packages=find_packages(),
    zip_safe=False,
    classifiers=['Programming Language :: Python :: 3'],
)
